version: '3'
services:
  mysql:
    image: mysql
    container_name: openai_helper_mysql
    ports:
      - "3306:3306"
    env_file:
      - db/config/.env
    environment:
      TZ: Asia/Seoul
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./db/mysql:/var/lib/mysql
    restart: always
  backend:
    build: ./openai-api
    container_name: openai_helper_backend
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8080:8080"
    volumes:
      - ./openai-api/build/libs/openai-api-1.0.0.jar:/app/app.jar
    restart: always
